<a href="https://colab.research.google.com/github/UserDs/test-repo/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# from google.colab import drive
# drive.mount('/content/gdrive')

In [ ]:
# linear algebra
import numpy as np 

# data processing
import pandas as pd 

In [ ]:
array_one = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [ ]:
array_one.size

9

In [ ]:
# adding an additional line

In [ ]:
# adding an additional line

**line1:** this is line 1
<br>
**line2:** this is line 2

In [ ]:
np.ones_like(np.zeros((4, 4)))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
array1 = np.arange(4)
array2 = array1.reshape(1, -1)

In [ ]:
array1

array([0, 1, 2, 3])

In [ ]:
array2

array([[0, 1, 2, 3]])

In [ ]:
array1 = np.random.randint(10, size = (3, 3))

In [ ]:
array1

array([[3, 9, 6],
       [6, 8, 8],
       [5, 4, 7]])